### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by epixtm** [acm-uic/acm-uic.github.io#664]
**Describe the bug**
I think people are already aware of this but I'd like to see it fixed since this seems to be where the majority of people in ACM/LUG are directing infrastructure docs to, and I'd like to start fleshing it out over the summer.

**To Reproduce**
1. Open `acm.cs.uic.edu` on a browser.
2. Click the search bar (or use Ctrl-K).
3. Searching for something relevant and realize nothing shows up.
4. Be confused.

**Expected behavior**
Relevant search results.

**Screenshots**
![image](https://user-images.githubusercontent.com/87404863/235333996-245af564-032c-453c-9fa3-4191a6f17bd3.png)

**Desktop (please complete the following information):**
OS: **GNU/Linux**
Browser: **Chromium**
Version: **112.0.5615.165**

**Comment by clee231** [comment]
I believe this is related to #629.

The search feature is something that was added recently. It's still being worked on. (#621, #613, acm-uic/IaC#28)

**Comment by clee231** [comment]
Latest build results are here: https://github.com/acm-uic/acm-uic.github.io/actions/runs/5171696094/jobs/9315433622

The pipeline seems to be failing because the pipeline is not authorized to create the GitHub Secret currently.
The current proposal is to pass the API key secret when triggering the website deployment instead of using GitHub Secrets.
